### ISSUE TITLE
How to Deal with interference (wiki)

### ISSUE THREAD

**Issue by domonetic** [gioblu/PJON#51] opened 2016-04-13 03:04 UTC
I understand that just connect 1 Data Cable works, but is there you got previous care, pullup resistors, diodes protection?
No it is not clear how protect in a noisy environment or outdoor use.
Can add this to wiki?

**Comment by gioblu** [comment] 2016-04-13 08:03
Ciao @domonetic. Hope all is going good.
Abolutely, you are right, maybe I should create a Wiki section dedicated to interference reduction.

**Comment by domonetic** [comment] 2016-04-13 13:53
Yes please. I try to test this lib with RF 100w more than 25 meters away. 
Do you test with Arduino pro micro?

**Comment by gioblu** [comment] 2016-04-13 14:42
Ciao @domonetic, 100w?? You are transmitting to mars :) or you mean mw ?
In any case I would be happy to help you, please if you can describe technically your setup and I will try to support you to get a decent communication channel.

- PJON (not PJON_ASK) is not tested on radio and probably is not effective because is a standard single sample in the middle of the bit, PJON_ASK uses a sort of "oversampling" I would call digital-pseudo-oversampling. 
- PJON is not tested with Arduino PRO micro (3.3v logic level could be a issue)!!! What is making me dubious is that maybe, you are using the logic pin of micro to feed radio tx and maybe the 3.3v produced are not enough to generate the radio waves intensity you need to cover the gap between receiver and transmitter.

**Comment by domonetic** [comment] 2016-04-13 15:17
I do not transmitting to Mars, but yes, to the rest of the world, I am amateur radio. The idea is digitalize a rotor antenna to find the position and display it in my rack. The transmit antenna (interference) is about 50cm cable distance, the control logic will be shielded by the rotor casing. Also as another serious interference that the power line is 24VAC.
I use arduino PROMICRO be 5v.

**Comment by gioblu** [comment] 2016-04-13 15:24
Fantastic, compliments :+1: !!!
Happy to know we have a radio amateur in the PJON community (I am attending the courses to get the call-sign here in Italy!). Do you have some sort of result with communication or you get absolute absence?  Are you using PJON or PJON_ASK implementation?

Possible fixes:
- Different power source
- Diode before power feeding to Arduino
- Pulldown resistor on the transmitting and receiving pin
- Different antenna design
- Tweak values of timing in PJON_ASK.h

**Comment by gioblu** [comment] 2016-04-13 15:29
@domonetic try also to use a Nano/Duemilanove/Uno to clarify if the problem is the board itself or the rest.

**Comment by domonetic** [comment] 2016-04-13 15:40
Great, I am LU4HNE when you have it we connect. Or if you do operational practice let me know.
I do not even armed myself because I have two scenarios to test. Before i need correct a minimal problem with movement of pot.

1. Potentiometer reading the crown
2. magnetometer or external Compass

And send readings to the base station and display

Also, you can send that want to position degrees, and make manual movements

**Comment by gioblu** [comment] 2016-04-13 15:46
Seems really an interesting project. When you will be working on it feel free to ask support here.
And if you want to share it done, soon we will release PJON's website where we will showcase some projects by the users. Happy tinkering.

**Comment by gioblu** [comment] 2016-04-13 15:47
@domonetic soon follows addon on the wiki as you requested.

**Comment by gioblu** [comment] 2016-04-13 18:17
Hi @domonetic , I am still working on it, but you can already take a look: https://github.com/gioblu/PJON/wiki/Deal-with-interference

**Comment by domonetic** [comment] 2016-04-13 19:08
Magnific!!. 
In buses rs485 are used TVS or diodes in opposition
This suppresses transient voltages, used olso in ADC systems

        ^ +vcc
         |    
        [=] DIODE
         |
PIN -------------- BUS
         |    
        [=] DIODE
         |
        --- GND


You think you can work here?

**Comment by gioblu** [comment] 2016-04-13 19:46
Never tested this approach. Can you please explain more clearly? I would be sure to have understood the circuit diagram!

**Comment by domonetic** [comment] 2016-04-13 20:13
![adc_hw](https://cloud.githubusercontent.com/assets/4523833/14507816/e47a2944-019a-11e6-89ee-b1709bdcc3c8.gif)
![4705-01_fig06](https://cloud.githubusercontent.com/assets/4523833/14507840/03b090b4-019b-11e6-8bd6-ea33aa307df8.jpg)

**Comment by domonetic** [comment] 2016-04-13 20:15
first. This method is used on inputs of home alarms
Second. More eficient protection used in rs485 buses.

**Comment by gioblu** [comment] 2016-04-14 12:32
Ciao @domonetic can you check in the new page wiki that, what you suggested is correctly explained?

**Comment by domonetic** [comment] 2016-04-14 13:57
Good!! im preparing my RF test. when it done i upload a video.

2016-04-14 9:32 GMT-03:00 Giovanni Blu Mitolo <notifications@github.com>:

> Ciao @domonetic <https://github.com/domonetic> can you check in the new
> page wiki that, what you suggested is correctly explained?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gioblu/PJON/issues/51#issuecomment-209915538>
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by gioblu** [comment] 2016-04-14 14:10
@domonetic Fantastic. Feel free to open an issue here to showcase your work. We will manage to add it in the application examples made by the contributors and users like you. Thank you again for your support and passion! (I will for now close this issue because seems we reached a satisfactory result)

**Comment by domonetic** [comment] 2016-04-15 17:46
hear a prototype
https://youtu.be/UtZoIAoqQns

Tomorrow the real test.

**Comment by gioblu** [comment] 2016-04-17 00:33
@domonetic I saw the video, compliments!!!! I am really curious to see the final result.

**Comment by olehs** [comment] 2016-04-17 08:48
@domonetic, the first pircture with protective diodes shows these diodes are already a part of the AVR (which is also described in Atmel's datasheet part about I/O pins internal protection).
As far as I understand, you suggest adding extra diodes for protection, right?

I also heard about PTC and Zener diode protection of IO pins, but don't really know if this approach is suitable for PJON protocol.

**Comment by domonetic** [comment] 2016-04-18 17:29
The PTC do not know if they work, the zener often cut off or slow pulses. It
is best to use tvs or high speed diodes. I think a couple of diodes helps
maintain healthy inputs and is not much to add them.

I simple tests with 15 meters of cable. but still it raining in my city and I
can not even try with rf

2016-04-17 5:48 GMT-03:00 olehs <notifications@github.com>:

> @domonetic <https://github.com/domonetic>, the first pircture with
> protective diodes shows these diodes are already a part of the AVR (which
> is also described in Atmel's datasheet part about I/O pins internal
> protection).
> As far as I understand, you suggest adding extra diodes for protection,
> right?
>
> I also heard about PTC and Zener diode protection of IO pins, but don't
> really know if this approach is suitable for PJON protocol.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gioblu/PJON/issues/51#issuecomment-210979457>
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by gioblu** [comment] 2016-04-25 21:49
Ciao @domonetic how its going with the rotor antenna experiment?
2.0 stable is finally out, give it a look! :)

**Comment by gioblu** [comment] 2016-04-25 21:52
Ah and if you can tell me if you consider the wiki page satisfactory and so this issue solved.

**Comment by domonetic** [comment] 2016-04-26 12:21
So far so good, I'm testing the magnetometer gives me a headache, so I open in
case of finding any error.
But with 15 meters of cable does not give any communication problems

2016-04-25 18:52 GMT-03:00 Giovanni Blu Mitolo <notifications@github.com>:

> Ah and if you can tell me if you consider the wiki page satisfactory and
> so this issue solved.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gioblu/PJON/issues/51#issuecomment-214538698>
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by gioblu** [comment] 2016-04-26 16:02
Good send us a video! I am so curious to see your application! 
Happy tinkering.

**Closed** 2016-04-29 13:13 UTC
Labels: enhancement
